### ISSUE TITLE
How do i convert the ID into a Date?

### ISSUE THREAD

**Issue by zuaaef** [shawnclovie/SpotFlake#1]
This is not working 
```
Date.init(timeIntervalSinceReferenceDate: Double(id.rawValue))
```

**Comment by shawnclovie** [comment]
The `rawValue` of ID is stored complex values, not seconds or nanoseconds since 1970. And, it is also based on `epoch` that the value you could change.

You can try this:
```swift
Date(timeIntervalSince1970: TimeInterval(id.time) / 1_000)
```
The `time` property would return milliseconds since 1970 yr.

I'll add property document later.
